### ISSUE TITLE
Maps for custom exercises

### ISSUE THREAD

**Issue by homemdasneves** [Fitbit/sdk-exercise#4]
Hi

Is is it possible that the summary for a gps-enabled custom exercise displays a map? I tested the skateboard app and there's no map on the summary, and I read on the forums that the Alpine Skiing app also doesn't show a map either. Is there any constraint on this? If it's possible, how can we achieve this?
I'm researching for a surf tracking app. Ideally, only the waves ridden would be plotted on the map.

Thanks in advance
Filipe

**Comment by orviwan** [comment]
GPS currently isn't supported for the custom exercise types, but it will hopefully be addressed soon. In the meantime, you'll need to use one of the existing exercise types which does have GPS enabled. I realize this it not ideal.

**Comment by homemdasneves** [comment]
But is the GPS data for custom exercises stored on the fitbit servers, so that it could be accessed through the web api? If so, we could visualize it with a custom companion app, right?

**Comment by orviwan** [comment]
I think it should be, but you'd need to check.
