### ISSUE TITLE
Custom exercise name

### ISSUE THREAD

**Issue by pfederi** [Fitbit/sdk-exercise#7]
When I use the Skateboard Exercise App everything works fine. The name oft the exercise is shown correctly and the map is shown correctly. As soon as I change to SUP or stand up paddling no app will be shown in the users exercise dashboard. A workaround is to put Cycling or run as exerciseType. But this will give a false name as output. As skateboarding is not defined as exerciseType [here](https://dev.fitbit.com/build/reference/device-api/exercise/) I was wondering if it could be possible to fix this issue. It worked in January but after an update it stopped working and I have a lot of confused users.

**Comment by orviwan** [comment]
Hi Patrick, we're aware of this issue and it requires some changes which will be coming in a forthcoming update. You're right though, stick with the standard types for now.

**Comment by fabiogomiero** [comment]
Hi @orviwan,
any news about this issue? I'm developping an app with custom name (_Kitesurf_) and I enabled GPS in the `exerciseOptions` but when I synchronize with mobile app the exercise name is `aerobic exercise` and no map is shown.
How does skateboard app do to show map and correct name?

Device: Ionic
Firmware: 27.33.1.30
Mobile app: 3.4.1
SDK: 3.1.0

**Comment by pfederi** [comment]
@orviwan any news on this issue? I have more then 100 users per month (over 1200 new users over the last year) who would like to use the app properly.

**Comment by orviwan** [comment]
There's actually 2 issues here, and neither have been resolved yet.

1. The Fitbit backend doesn't know how to display your custom exercises (is it a custom swim, does it need a map etc).
2. The device doesn't know which type of algorithm to use for the custom exercise. There's abmulatory/non abulatory, indoor/outdoor, plus some others.

We're still looking at how we can adapt the API to make it cover these cases.

**Comment by hemanthnarayanan123** [comment]
any updates on the issue#1?. Its weird that the app taken in a custom activity Name but the backend cannot display that name.
